tenant: gillkyle 
app: greenhouse
service: greenhouse-job-application
plugins:
  - serverless-dotenv-plugin
  
frameworkVersion: ">=1.44.0"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  postApplication:
    handler: handler.postApplication
    environment: 
      GATSBY_GREENHOUSE_KEY: ${env:GATSBY_GREENHOUSE_KEY}
    
    events:
      - http:
          path: postApplication
          method: post
          cors: true
